package models;
    
public class ChocoProvidableTable{    
    
    private String providableServiceIdNum;
    private String providableServiceDescription;
    
    public String getProvidableServiceIdNum() {
        return providableServiceIdNum;
    }
    
    public void setProvidableServiceIdNum(String providableServiceIdNum) {
        this.providableServiceIdNum = providableServiceIdNum;
    }
    
    public String getProvidableServiceDescription() {
        return providableServiceDescription;
    }
    
    public void setProvidableServiceDescription(String providableServiceDescription) {
        this.providableServiceDescription = providableServiceDescription;
    }
    
} // Class generated by : Benjamin Haos
