package models;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class ProviderModel {
    private Map<String, Object> provider;

    /**
     * Constructor
     */
    public ProviderModel() {
        this.provider = new HashMap<>();
    }
    
    public int createProvider(String providerNumber, String providerName, String providerStreetAddress, String providerCity, String providerState, long providerZip, boolean isDietitian, boolean isExerciseExpert, boolean isInternist){
        
        ProviderTable usr = new ProviderTable();

        usr.setProviderNumber(providerNumber);
        usr.setProviderName(providerName);
        usr.setProviderStreetAddress(providerStreetAddress);
        usr.setProviderCity(providerCity);
        usr.setProviderState(providerState);
        usr.setProviderZip(providerZip);
        usr.setIsDietitian(isDietitian);
        usr.setIsExerciseExpert(isExerciseExpert);
        usr.setIsInternist(isInternist);
        provider.put(providerNumber, usr);
    
        return 1;
    }
    
    /**
     * Check to find if a user is available
     * @param id
     * @return
     */
    public boolean checkProvider(String id) {
        Iterator it = provider.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry pair = (Map.Entry)it.next();
            ProviderTable u = (ProviderTable)pair.getValue();
            if((u.getProviderNumber().equals(id)))
                return false;
        }
        return true;
    }
    
    public int updateProvider(String providerNumber, String providerName, String providerStreetAddress, String providerCity, String providerState, long providerZip, boolean isDietitian, boolean isExerciseExpert, boolean isInternist){

        ProviderTable usr = (ProviderTable)provider.get(providerNumber);

        usr.setProviderName(providerName);
        usr.setProviderStreetAddress(providerStreetAddress);
        usr.setProviderCity(providerCity);
        usr.setProviderState(providerState);
        usr.setProviderZip(providerZip);
        usr.setIsDietitian(isDietitian);
        usr.setIsExerciseExpert(isExerciseExpert);
        usr.setIsInternist(isInternist);
        provider.put(providerNumber, usr);
    
        return 1;
    }
    
    public boolean removeProvider(String id) {
        if(!checkProvider(id)) {
            provider.remove(id);
            return true;    
        }
        return false;
    }
    public List sendElements() {
        List<Object> ret = new ArrayList<>(provider.values());
        return ret;
    }

    public List sendProvidersId() {
        List<Object> ret = new ArrayList<>(provider.keySet());
        return ret;
    }

} // Class generated by : Benjamin Haos
