package models;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class ServiceModel {
    private Map<String, Object> service;

    /**
     * Constructor
     */
    public ServiceModel() {
        this.service = new HashMap<>();
    }
    
    public int createService(String providableServiceIdNum, String providableServiceDescription, boolean isProvidableByDietitian, boolean isProvidableByExerciseExpert, boolean isProvidableByInternist){
        
        ServiceTable usr = new ServiceTable();

        usr.setProvidableServiceIdNum(providableServiceIdNum);
        usr.setProvidableServiceDescription(providableServiceDescription);
        usr.setIsProvidableByDietitian(isProvidableByDietitian);
        usr.setIsProvidableByExerciseExpert(isProvidableByExerciseExpert);
        usr.setIsProvidableByInternist(isProvidableByInternist);
        service.put(providableServiceIdNum, usr);
    
        return 1;
    }
    
    /**
     * Check to find if a user is available
     * @param id
     * @return
     */
    public boolean checkService(String id) {
        Iterator it = service.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry pair = (Map.Entry)it.next();
            ServiceTable u = (ServiceTable)pair.getValue();
            if((u.getProvidableServiceIdNum().equals(id)))
                return false;
        }
        return true;
    }
    
    public int updateService(String providableServiceIdNum, String providableServiceDescription, boolean isProvidableByDietitian, boolean isProvidableByExerciseExpert, boolean isProvidableByInternist){

        ServiceTable usr = (ServiceTable)service.get(providableServiceIdNum);

        usr.setProvidableServiceDescription(providableServiceDescription);
        usr.setIsProvidableByDietitian(isProvidableByDietitian);
        usr.setIsProvidableByExerciseExpert(isProvidableByExerciseExpert);
        usr.setIsProvidableByInternist(isProvidableByInternist);
        service.put(providableServiceIdNum, usr);
    
        return 1;
    }
    
    public boolean removeService(String id) {
        if(!checkService(id)) {
            service.remove(id);
            return true;    
        }
        return false;
    }
    public List sendElements() {
        List<Object> ret = new ArrayList<>(service.values());
        return ret;
    }

    public List sendServicesId() {
        List<Object> ret = new ArrayList<>(service.keySet());
        return ret;
    }

} // Class generated by : Benjamin Haos
