package models;
    
public class ServiceTable{    
    
    private String providableServiceIdNum;
    private String providableServiceDescription;
    private boolean isProvidableByDietitian;
    private boolean isProvidableByExerciseExpert;
    private boolean isProvidableByInternist;
    
    public String getProvidableServiceIdNum() {
        return providableServiceIdNum;
    }
    
    public void setProvidableServiceIdNum(String providableServiceIdNum) {
        this.providableServiceIdNum = providableServiceIdNum;
    }
    
    public String getProvidableServiceDescription() {
        return providableServiceDescription;
    }
    
    public void setProvidableServiceDescription(String providableServiceDescription) {
        this.providableServiceDescription = providableServiceDescription;
    }
    
    public boolean getIsProvidableByDietitian() {
        return isProvidableByDietitian;
    }
    
    public void setIsProvidableByDietitian(boolean isProvidableByDietitian) {
        this.isProvidableByDietitian = isProvidableByDietitian;
    }
    
    public boolean getIsProvidableByExerciseExpert() {
        return isProvidableByExerciseExpert;
    }
    
    public void setIsProvidableByExerciseExpert(boolean isProvidableByExerciseExpert) {
        this.isProvidableByExerciseExpert = isProvidableByExerciseExpert;
    }
    
    public boolean getIsProvidableByInternist() {
        return isProvidableByInternist;
    }
    
    public void setIsProvidableByInternist(boolean isProvidableByInternist) {
        this.isProvidableByInternist = isProvidableByInternist;
    }
    
} // Class generated by : Benjamin Haos
