package models;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class UserModel {
    private Map<String, Object> user;

    /**
     * Constructor
     */
    public UserModel() {
        this.user = new HashMap<>();
    }
    
    public int createUser(String memberNumber, String memberName, String memberStreetAddress, String memberCity, String memberState, long memberZip){
        
        UserTable usr = new UserTable();

        usr.setMemberNumber(memberNumber);
        usr.setMemberName(memberName);
        usr.setMemberStreetAddress(memberStreetAddress);
        usr.setMemberCity(memberCity);
        usr.setMemberState(memberState);
        usr.setMemberZip(memberZip);
        user.put(memberNumber, usr);
    
        return 1;
    }
    
    /**
     * Check to find if a user is available
     * @param id
     * @return
     */
    public boolean checkUser(String id) {
        Iterator it = user.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry pair = (Map.Entry)it.next();
            UserTable u = (UserTable)pair.getValue();
            if((u.getMemberNumber().equals(id)))
                return false;
        }
        return true;
    }
    
    public int updateUser(String memberNumber, String memberName, String memberStreetAddress, String memberCity, String memberState, long memberZip){

        UserTable usr = (UserTable)user.get(memberNumber);

        usr.setMemberName(memberName);
        usr.setMemberStreetAddress(memberStreetAddress);
        usr.setMemberCity(memberCity);
        usr.setMemberState(memberState);
        usr.setMemberZip(memberZip);
        user.put(memberNumber, usr);
    
        return 1;
    }
    
    public boolean removeUser(String id) {
        if(!checkUser(id)) {
            user.remove(id);
            return true;    
        }
        return false;
    }
    public List sendElements() {
        List<Object> ret = new ArrayList<>(user.values());
        return ret;
    }

    public List sendUsersId() {
        List<Object> ret = new ArrayList<>(user.keySet());
        return ret;
    }

} // Class generated by : Benjamin Haos
