setEntityBillableIdNumber("")
setMemberNumberService("")
setProviderNumberServicing("")
setServiceNumberServiced("")
setDateServiced("")
setDateServicedRecorded("")
setServiceCost()
setServiceComment("")