package entities;

import org.joda.time.*;

import org.springframework.data.annotation.Id;

public class Billable extends Validable{    

    private String entityBillableIdNumber;
    private String memberNumberService;
    private String providerNumberServicing;
    private String serviceNumberServiced;
    private DateTime dateServiced;
    private DateTime dateServicedRecorded;
    private double serviceCost;
    private String serviceComment;
    
    public String getEntityBillableIdNumber() {
        return entityBillableIdNumber;
    }
    
    public void setEntityBillableIdNumber(String entityBillableIdNumber) {
        this.entityBillableIdNumber = entityBillableIdNumber;
    }
    
    public String getMemberNumberService() {
        return memberNumberService;
    }
    
    public void setMemberNumberService(String memberNumberService) {
        this.memberNumberService = memberNumberService;
    }
    
    public String getProviderNumberServicing() {
        return providerNumberServicing;
    }
    
    public void setProviderNumberServicing(String providerNumberServicing) {
        this.providerNumberServicing = providerNumberServicing;
    }
    
    public String getServiceNumberServiced() {
        return serviceNumberServiced;
    }
    
    public void setServiceNumberServiced(String serviceNumberServiced) {
        this.serviceNumberServiced = serviceNumberServiced;
    }
    
    public String getDateServiced() {
        if(dateServiced == null)
            return null;
        return dateServiced.toString("MM/dd/yyyy");
    }
    
    public void setDateServiced(String dateServiced) {
        
        String tempString = "";
        tempString = dateServiced.substring(dateServiced.lastIndexOf("/")+1) + "-";
        tempString += dateServiced.substring(0, dateServiced.indexOf("/")) + "-";
        tempString += dateServiced.substring((dateServiced.indexOf("/")+1), dateServiced.lastIndexOf("/"));
        
        
        this.dateServiced = new DateTime(tempString);
    }
    
    public String getDateServicedRecorded() {
        if(dateServicedRecorded == null)
            return null;
        return dateServicedRecorded.toString("MM/dd/yyyy HH:mm:ss");
    }

    public DateTime getDateTimeServicedRecorded(){
         DateTime returnDateTime = new DateTime(dateServicedRecorded.toString());
         return returnDateTime;
    }   
    // This is used when a new entity is created.
    public void setDateServicedRecorded() {
        
        DateTime dateTimeCreated = new DateTime();
        
        System.out.println("setDateServicedRecorded called!");
        System.out.println("dateTimeCreated = " + dateTimeCreated.toString("MM/dd/yyyy HH:mm:ss"));

        this.dateServicedRecorded = dateTimeCreated;
    }
    
    // This is used for creating test data.
    public void setDateServicedRecorded(String dateServicedRecorded) {
        this.dateServicedRecorded = new DateTime(dateServicedRecorded);
    }
    
    public double getServiceCost() {
        return serviceCost;
    }
    
    public void setServiceCost(double serviceCost) {
        this.serviceCost = serviceCost;
    }
    
    public String getServiceComment() {
        return serviceComment;
    }
    
    public void setServiceComment(String serviceComment) {
        this.serviceComment = serviceComment;
    }
    
} // Class generated by : Benjamin Haos
