package entities;

import org.joda.time.*;

import org.springframework.data.annotation.Id;

public class Billable extends Validable{    

    private String entityBillableIdNumber;
    private String memberNumberService;
    private String providerNumberServicing;
    private DateTime dateServiced;
    private DateTime dateServicedRecorded;
    private double serviceCost;
    private String serviceComment;
    
    public String getEntityBillableIdNumber() {
        return entityBillableIdNumber;
    }
    
    public void setEntityBillableIdNumber(String entityBillableIdNumber) {
        this.entityBillableIdNumber = entityBillableIdNumber;
    }
    
    public String getMemberNumberService() {
        return memberNumberService;
    }
    
    public void setMemberNumberService(String memberNumberService) {
        this.memberNumberService = memberNumberService;
    }
    
    public String getProviderNumberServicing() {
        return providerNumberServicing;
    }
    
    public void setProviderNumberServicing(String providerNumberServicing) {
        this.providerNumberServicing = providerNumberServicing;
    }
    
    public String getDateServiced() {
        return dateServiced.toString("MM/dd/yyyy");
    }
    
    public void setDateServiced(String dateServiced) {
        
        String tempString = "";
        tempString = dateServiced.substring(dateServiced.lastIndexOf("/")+1) + "-";
        tempString += dateServiced.substring(0, dateServiced.indexOf("/")) + "-";
        tempString += dateServiced.substring((dateServiced.indexOf("/")+1), dateServiced.lastIndexOf("/"));
        
        this.dateServiced = new DateTime(tempString);
    }
    
    public String getDateServicedRecorded() {
        return dateServicedRecorded.toString("MM/dd/yyyy");
    }
    
    public void setDateServicedRecorded(String dateServicedRecorded) {
        
        String tempString = "";
        tempString = dateServicedRecorded.substring(dateServicedRecorded.lastIndexOf("/")+1) + "-";
        tempString += dateServicedRecorded.substring(0, dateServicedRecorded.indexOf("/")) + "-";
        tempString += dateServicedRecorded.substring((dateServicedRecorded.indexOf("/")+1), dateServicedRecorded.lastIndexOf("/"));
        
        this.dateServicedRecorded = new DateTime(tempString);
    }
    
    public double getServiceCost() {
        return serviceCost;
    }
    
    public void setServiceCost(double serviceCost) {
        this.serviceCost = serviceCost;
    }
    
    public String getServiceComment() {
        return serviceComment;
    }
    
    public void setServiceComment(String serviceComment) {
        this.serviceComment = serviceComment;
    }
    
} // Class generated by : Benjamin Haos
