package entities;
    
public class Provider implements Validable{    
    
    private String providerNumber;
    private String providerName;
    private String providerStreetAddress;
    private String providerCity;
    private String providerState;
    private long providerZip;
    private boolean isDietitian;
    private boolean isExerciseExpert;
    private boolean isInternist;
    
    public String getProviderNumber() {
        return providerNumber;
    }
    
    public void setProviderNumber(String providerNumber) {
        this.providerNumber = providerNumber;
    }
    
    public String getProviderName() {
        return providerName;
    }
    
    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }
    
    public String getProviderStreetAddress() {
        return providerStreetAddress;
    }
    
    public void setProviderStreetAddress(String providerStreetAddress) {
        this.providerStreetAddress = providerStreetAddress;
    }
    
    public String getProviderCity() {
        return providerCity;
    }
    
    public void setProviderCity(String providerCity) {
        this.providerCity = providerCity;
    }
    
    public String getProviderState() {
        return providerState;
    }
    
    public void setProviderState(String providerState) {
        this.providerState = providerState;
    }
    
    public long getProviderZip() {
        return providerZip;
    }
    
    public void setProviderZip(long providerZip) {
        this.providerZip = providerZip;
    }
    
    public boolean getIsDietitian() {
        return isDietitian;
    }
    
    public void setIsDietitian(boolean isDietitian) {
        this.isDietitian = isDietitian;
    }
    
    public boolean getIsExerciseExpert() {
        return isExerciseExpert;
    }
    
    public void setIsExerciseExpert(boolean isExerciseExpert) {
        this.isExerciseExpert = isExerciseExpert;
    }
    
    public boolean getIsInternist() {
        return isInternist;
    }
    
    public void setIsInternist(boolean isInternist) {
        this.isInternist = isInternist;
    }
    
    @Override
    public boolean isValid() {
        if(this.providerNumber == null || this.providerNumber.length() != 9) return false;
        for(int i = 0; i < this.providerNumber.length(); i++){
            if(!Character.isDigit(this.providerNumber.charAt(i)))
                return false;
        }
        if(this.providerName == null || this.providerName.length() > 25)
            return false;
        if(this.providerStreetAddress == null || this.providerStreetAddress.length() > 25)
            return false;
        if(this.providerCity == null || this.providerCity.length() > 25)
            return false;
        if(this.providerState == null || this. providerState.length() > 25)
            return false;
        if(this.providerZip == 0 || (String.valueOf(this.providerZip)).length() != 5)
            return false;
        for(int i = 0; i < (String.valueOf(this.providerZip)).length(); i++){
            if(!Character.isDigit((String.valueOf(this.providerZip)).charAt(i)))
                return false;
        }
        return true;
    }
}
// Class generated by : Benjamin Haos
// isValid method by : Zachary Brunette