package entities;
    
public class Service implements Validable{    
    
    private String providableServiceIdNum;
    private String providableServiceDescription;
    private boolean isProvidableByDietitian;
    private boolean isProvidableByExerciseExpert;
    private boolean isProvidableByInternist;
    
    public String getProvidableServiceIdNum() {
        return providableServiceIdNum;
    }
    
    public void setProvidableServiceIdNum(String providableServiceIdNum) {
        this.providableServiceIdNum = providableServiceIdNum;
    }
    
    public String getProvidableServiceDescription() {
        return providableServiceDescription;
    }
    
    public void setProvidableServiceDescription(String providableServiceDescription) {
        this.providableServiceDescription = providableServiceDescription;
    }
    
    public boolean getIsProvidableByDietitian() {
        return isProvidableByDietitian;
    }
    
    public void setIsProvidableByDietitian(boolean isProvidableByDietitian) {
        this.isProvidableByDietitian = isProvidableByDietitian;
    }
    
    public boolean getIsProvidableByExerciseExpert() {
        return isProvidableByExerciseExpert;
    }
    
    public void setIsProvidableByExerciseExpert(boolean isProvidableByExerciseExpert) {
        this.isProvidableByExerciseExpert = isProvidableByExerciseExpert;
    }
    
    public boolean getIsProvidableByInternist() {
        return isProvidableByInternist;
    }
    
    public void setIsProvidableByInternist(boolean isProvidableByInternist) {
        this.isProvidableByInternist = isProvidableByInternist;
    }
    
    @Override
    public boolean isValid() {
        if(this.providableServiceIdNum == null || this.providableServiceIdNum.length() != 6) return false;
        for(int i = 0; i < this.providableServiceIdNum.length(); i++){
            if(!Character.isDigit(this.providableServiceIdNum.charAt(i)))
                return false;
        }
        if(this.providableServiceDescription == null || this.providableServiceDescription.length() > 20)
            return false;
        return true;
    }
    
}
// Class generated by : Benjamin Haos
// isValid method by : Zachary Brunette