package entities;
    
public class Service implements Validable{    
    
    private String providableServiceIdNum;
    private String providableServiceDescription;
    
    public String getProvidableServiceIdNum() {
        return providableServiceIdNum;
    }
    
    public void setProvidableServiceIdNum(String providableServiceIdNum) {
        this.providableServiceIdNum = providableServiceIdNum;
    }
    
    public String getProvidableServiceDescription() {
        return providableServiceDescription;
    }
    
    public void setProvidableServiceDescription(String providableServiceDescription) {
        this.providableServiceDescription = providableServiceDescription;
    }
    
    @Override
    public boolean isValid() {
        
        // TODO : CODE THIS!
        return true;
    }
    
} // Class generated by : Benjamin Haos
