package entities;

import org.springframework.data.annotation.Id;

public class Service extends Validable{    

    private String entityServiceIdNumber;
    private String providableServiceDescription;
    private boolean isProvidableByDietitian;
    private boolean isProvidableByExerciseExpert;
    private boolean isProvidableByInternist;
    
    public String getEntityServiceIdNumber() {
        return entityServiceIdNumber;
    }
    
    public void setEntityServiceIdNumber(String entityServiceIdNumber) {
        this.entityServiceIdNumber = entityServiceIdNumber;
    }
    
    public String getProvidableServiceDescription() {
        return providableServiceDescription;
    }
    
    public void setProvidableServiceDescription(String providableServiceDescription) {
        this.providableServiceDescription = providableServiceDescription;
    }
    
    public boolean getIsProvidableByDietitian() {
        return isProvidableByDietitian;
    }
    
    public void setIsProvidableByDietitian(boolean isProvidableByDietitian) {
        this.isProvidableByDietitian = isProvidableByDietitian;
    }
    
    public boolean getIsProvidableByExerciseExpert() {
        return isProvidableByExerciseExpert;
    }
    
    public void setIsProvidableByExerciseExpert(boolean isProvidableByExerciseExpert) {
        this.isProvidableByExerciseExpert = isProvidableByExerciseExpert;
    }
    
    public boolean getIsProvidableByInternist() {
        return isProvidableByInternist;
    }
    
    public void setIsProvidableByInternist(boolean isProvidableByInternist) {
        this.isProvidableByInternist = isProvidableByInternist;
    }
    
} // Class generated by : Benjamin Haos
