package entities;

import org.joda.time.*;

import org.springframework.data.annotation.Id;

public class User extends Validable{    

    private String entityUserIdNumber;
    private String memberName;
    private String memberStreetAddress;
    private String memberCity;
    private String memberState;
    private long memberZip;
    private DateTime memberValidThrough;
    
    public String getEntityUserIdNumber() {
        return entityUserIdNumber;
    }
    
    public void setEntityUserIdNumber(String entityUserIdNumber) {
        this.entityUserIdNumber = entityUserIdNumber;
    }
    
    public String getMemberName() {
        return memberName;
    }
    
    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }
    
    public String getMemberStreetAddress() {
        return memberStreetAddress;
    }
    
    public void setMemberStreetAddress(String memberStreetAddress) {
        this.memberStreetAddress = memberStreetAddress;
    }
    
    public String getMemberCity() {
        return memberCity;
    }
    
    public void setMemberCity(String memberCity) {
        this.memberCity = memberCity;
    }
    
    public String getMemberState() {
        return memberState;
    }
    
    public void setMemberState(String memberState) {
        this.memberState = memberState;
    }
    
    public long getMemberZip() {
        return memberZip;
    }
    
    public void setMemberZip(long memberZip) {
        this.memberZip = memberZip;
    }
    
    public String getMemberValidThrough() {
        return memberValidThrough.toString("MM/dd/yyyy");
    }
    
    public void setMemberValidThrough(String memberValidThrough) {
        
        String tempString = "";
        tempString = memberValidThrough.substring(memberValidThrough.lastIndexOf("/")+1) + "-";
        tempString += memberValidThrough.substring(0, memberValidThrough.indexOf("/")) + "-";
        tempString += memberValidThrough.substring((memberValidThrough.indexOf("/")+1), memberValidThrough.lastIndexOf("/"));
        
        this.memberValidThrough = new DateTime(tempString);
    }
    
} // Class generated by : Benjamin Haos
